package NG.Entities;

import NG.Blocks.BlockSubGrid;
import org.joml.Vector3f;

/**
 * a block that may generate force in the direction of positive X
 * @author Geert van Ieperen created on 27-9-2019.
 */
public interface ForceGeneratingBlock {

    void update(float gameTime, float deltaTime, float activation);

    /**
     * calculates the force generated by this object, assuming it is on the given position
     * @return the force in Newton generated by this object towards positive x in local space
     */
    float getForce();

    Vector3f getDirection(BlockSubGrid grid);
}
